export interface QuantSymbol {
  symbol: string;
  name: string;
  category: "crypto" | "tech" | "etf" | "growth" | "bluechip";
  exchange: "Binance" | "NASDAQ" | "NYSE";
}

export const QUANT_SYMBOL_UNIVERSE: QuantSymbol[] = [
  // ── Crypto Majors (Binance Spot / Perpetual pairs) ───────────────────────
  { symbol: "BINANCE:BTCUSDT", name: "Bitcoin / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:ETHUSDT", name: "Ethereum / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:SOLUSDT", name: "Solana / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:BNBUSDT", name: "BNB / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:XRPUSDT", name: "Ripple / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:DOGEUSDT", name: "Dogecoin / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:ADAUSDT", name: "Cardano / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:AVAXUSDT", name: "Avalanche / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:LINKUSDT", name: "Chainlink / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:SUIUSDT", name: "Sui / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:NEARUSDT", name: "NEAR Protocol / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:APTUSDT", name: "Aptos / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:PEPEUSDT", name: "Pepe / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:SHIBUSDT", name: "Shiba Inu / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:DOTUSDT", name: "Polkadot / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:LTCUSDT", name: "Litecoin / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:BCHUSDT", name: "Bitcoin Cash / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:UNIUSDT", name: "Uniswap / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:ATOMUSDT", name: "Cosmos / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:RENDERUSDT", name: "Render / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:FETUSDT", name: "Artificial Superintelligence", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:TAOUSDT", name: "Bittensor / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:INJUSDT", name: "Injective / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:ARBUSDT", name: "Arbitrum / Tether", category: "crypto", exchange: "Binance" },
  { symbol: "BINANCE:OPUSDT", name: "Optimism / Tether", category: "crypto", exchange: "Binance" },

  // ── Tech Mega-Caps & Semis ───────────────────────────────────────────────
  { symbol: "NVDA", name: "NVIDIA Corp.", category: "tech", exchange: "NASDAQ" },
  { symbol: "AAPL", name: "Apple Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "MSFT", name: "Microsoft Corp.", category: "tech", exchange: "NASDAQ" },
  { symbol: "AMZN", name: "Amazon.com Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Google)", category: "tech", exchange: "NASDAQ" },
  { symbol: "META", name: "Meta Platforms Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "TSLA", name: "Tesla Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "AVGO", name: "Broadcom Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "AMD", name: "Advanced Micro Devices", category: "tech", exchange: "NASDAQ" },
  { symbol: "QCOM", name: "Qualcomm Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "ORCL", name: "Oracle Corp.", category: "tech", exchange: "NYSE" },
  { symbol: "CRM", name: "Salesforce Inc.", category: "tech", exchange: "NYSE" },
  { symbol: "ADBE", name: "Adobe Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "NFLX", name: "Netflix Inc.", category: "tech", exchange: "NASDAQ" },
  { symbol: "INTC", name: "Intel Corp.", category: "tech", exchange: "NASDAQ" },
  { symbol: "ARM", name: "Arm Holdings plc", category: "tech", exchange: "NASDAQ" },
  { symbol: "MU", name: "Micron Technology", category: "tech", exchange: "NASDAQ" },
  { symbol: "SMCI", name: "Super Micro Computer", category: "tech", exchange: "NASDAQ" },

  // ── Index & Sector ETFs ──────────────────────────────────────────────────
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", category: "etf", exchange: "NYSE" },
  { symbol: "QQQ", name: "Invesco QQQ Trust (Nasdaq 100)", category: "etf", exchange: "NASDAQ" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", category: "etf", exchange: "NYSE" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average", category: "etf", exchange: "NYSE" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", category: "etf", exchange: "NASDAQ" },
  { symbol: "SOXX", name: "iShares Semiconductor ETF", category: "etf", exchange: "NASDAQ" },
  { symbol: "XLK", name: "Technology Select Sector SPDR", category: "etf", exchange: "NYSE" },
  { symbol: "XLF", name: "Financial Select Sector SPDR", category: "etf", exchange: "NYSE" },
  { symbol: "XLE", name: "Energy Select Sector SPDR", category: "etf", exchange: "NYSE" },
  { symbol: "XLV", name: "Health Care Select Sector SPDR", category: "etf", exchange: "NYSE" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR", category: "etf", exchange: "NYSE" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond", category: "etf", exchange: "NASDAQ" },
  { symbol: "GLD", name: "SPDR Gold Shares", category: "etf", exchange: "NYSE" },
  { symbol: "SLV", name: "iShares Silver Trust", category: "etf", exchange: "NYSE" },
  { symbol: "USO", name: "United States Oil Fund", category: "etf", exchange: "NYSE" },

  // ── High-Beta & Crypto Proxies ───────────────────────────────────────────
  { symbol: "MSTR", name: "MicroStrategy Inc. (BTC Proxy)", category: "growth", exchange: "NASDAQ" },
  { symbol: "COIN", name: "Coinbase Global Inc.", category: "growth", exchange: "NASDAQ" },
  { symbol: "MARA", name: "MARA Holdings (Marathon Digital)", category: "growth", exchange: "NASDAQ" },
  { symbol: "RIOT", name: "Riot Platforms Inc.", category: "growth", exchange: "NASDAQ" },
  { symbol: "CLSK", name: "CleanSpark Inc.", category: "growth", exchange: "NASDAQ" },
  { symbol: "HOOD", name: "Robinhood Markets Inc.", category: "growth", exchange: "NASDAQ" },
  { symbol: "PLTR", name: "Palantir Technologies", category: "growth", exchange: "NYSE" },
  { symbol: "UBER", name: "Uber Technologies Inc.", category: "growth", exchange: "NYSE" },
  { symbol: "ABNB", name: "Airbnb Inc.", category: "growth", exchange: "NASDAQ" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", category: "growth", exchange: "NASDAQ" },
  { symbol: "PANW", name: "Palo Alto Networks", category: "growth", exchange: "NASDAQ" },
  { symbol: "SHOP", name: "Shopify Inc.", category: "growth", exchange: "NYSE" },
  { symbol: "SNOW", name: "Snowflake Inc.", category: "growth", exchange: "NYSE" },
  { symbol: "DDOG", name: "Datadog Inc.", category: "growth", exchange: "NASDAQ" },
  { symbol: "NET", name: "Cloudflare Inc.", category: "growth", exchange: "NYSE" },
  { symbol: "SQ", name: "Block Inc.", category: "growth", exchange: "NYSE" },

  // ── Blue-Chip & Defensive ────────────────────────────────────────────────
  { symbol: "JPM", name: "JPMorgan Chase & Co.", category: "bluechip", exchange: "NYSE" },
  { symbol: "BAC", name: "Bank of America Corp.", category: "bluechip", exchange: "NYSE" },
  { symbol: "GS", name: "Goldman Sachs Group Inc.", category: "bluechip", exchange: "NYSE" },
  { symbol: "V", name: "Visa Inc.", category: "bluechip", exchange: "NYSE" },
  { symbol: "MA", name: "Mastercard Incorporated", category: "bluechip", exchange: "NYSE" },
  { symbol: "WMT", name: "Walmart Inc.", category: "bluechip", exchange: "NYSE" },
  { symbol: "COST", name: "Costco Wholesale Corp.", category: "bluechip", exchange: "NASDAQ" },
  { symbol: "LLY", name: "Eli Lilly and Co.", category: "bluechip", exchange: "NYSE" },
  { symbol: "UNH", name: "UnitedHealth Group", category: "bluechip", exchange: "NYSE" },
  { symbol: "XOM", name: "Exxon Mobil Corp.", category: "bluechip", exchange: "NYSE" },
  { symbol: "CAT", name: "Caterpillar Inc.", category: "bluechip", exchange: "NYSE" },
  { symbol: "BA", name: "Boeing Co.", category: "bluechip", exchange: "NYSE" }
];
